server:
  port: 80
  servlet:
    context-path: /se7en-boot
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: true
  security:
    user:
      name: admin
      password: 123456

